- hosts: all
  tasks:
  # enable EPEL repo by installing the epel-release package
  - name: EPEL repoをインストール
    become: yes
    yum: name=epel-release state=present

  # httpdのインストール
  - name: httpdをインストール
    yum:
      name: httpd
      state: present
  # httpdの起動
  - name: httpdを起動
    systemd:
      name: httpd
      state: started

  # Javaがインストールされているか確認
  - name: javaの存在確認
    shell: which java
    register: java_which
    failed_when: java_which.rc not in [0, 1]

  # javaがインストールされていない場合Javaをインストール
  - name: Java 17をインストール
    yum:
      name: https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm
      state: present
    when: java_which.rc == 1

  # yum clean all
  - name: clean
    command: yum clean all

  # mariadb-libs削除
  - name: remove mariadb-libs
    yum:
      state: absent
      name: mariadb-libs

  # Install MySQL
  - name: install mysql repository
    yum:
      state: present
      name: http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm
      validate_certs: yes

  - name: Install mysql packages
    yum: name={{item}} state=present
    with_items:
      - mysql-community-server
      - mysql-community-client
      - mysql-community-devel

  - name: Install mysql utilities
    yum: name={{item}} state=present
    with_items:
      - mysql-utilities
      - MySQL-python

  - name: MySQLを起動
    systemd:
      name: mysqld
      state: started
      enabled: yes

  # library-uiアプリを停止
  - name: library-uiアプリを停止
    command: ./jar_controller.sh off ui

  # library-apiアプリを停止
  - name: library-apiアプリを停止
    command: ./jar_controller.sh off api

  # プログラムファイル転送
  - name: APIファイルを送る
    synchronize:
      src: ~/practice/Java/library-api/target/library-api-0.0.1-SNAPSHOT.jar
      dest: ~/
  - name: UIファイルを送る
    synchronize:
      src: ~/practice/Java/library-ui/target/library-ui-0.0.1-SNAPSHOT.jar
      dest: ~/
  - name: jar_controllerファイルを送る
    synchronize:
      src: ~/practice/Java/library-api/jar_controller.sh
      dest: ~/
  - name: SQLファイルを送る
    synchronize:
      src: ~/practice/Java/library-api/src/main/resources/bookDBinit.sql
      dest: ~/

#  # library-apiアプリを起動
#  - name: library-apiアプリを起動
#    command: ./jar_controller.sh on api
#
#  # library-uiアプリを起動
#  - name: library-uiアプリを起動
#    command: ./jar_controller.sh on ui