- hosts: all
  tasks:

  - name: MySQL5.7をインストール
    yum:
      name: http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
      state: present
  - name: install necessary libraries
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - mysql-community-server
      - MySQL-python
      - yum-utils

  - name: mysql57-communityを有効化
    shell: |
      yum-config-manager --disable mysql80-community
      yum-config-manager --enable mysql57-community

  - name: mysql-community-clientをインストール
    yum:
      name: mysql-community-client
      state: present

  - name: MySQLを起動
    service:
      name: mysqld
      state: started
      enabled: yes